# Generated by Django 6.0 on 2025-12-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=30, unique=True)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('trailer_type', models.CharField(choices=[('dry_van', 'Dry Van'), ('reefer', 'Reefer'), ('flatbed', 'Flatbed'), ('step_deck', 'Step Deck'), ('other', 'Other')], default='dry_van', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_shop', 'In Shop'), ('inactive', 'Inactive'), ('sold', 'Sold')], default='active', max_length=10)),
                ('registration_expiration', models.DateField(blank=True, null=True)),
                ('inspection_expiration', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trailer',
                'verbose_name_plural': 'Trailers',
                'ordering': ['unit_number'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=30, unique=True)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_shop', 'In Shop'), ('inactive', 'Inactive'), ('sold', 'Sold')], default='active', max_length=10)),
                ('registration_expiration', models.DateField(blank=True, null=True)),
                ('inspection_expiration', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Truck',
                'verbose_name_plural': 'Trucks',
                'ordering': ['unit_number'],
            },
        ),
    ]
