# Generated by Django 6.0 on 2025-12-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('middle_name', models.CharField(blank=True, max_length=80, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ssn_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('ssn_full', models.CharField(blank=True, max_length=11, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pay_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat Rate'), ('cpm', 'Cents Per Mile')], default='percentage', max_length=20)),
                ('default_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('default_flat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('default_cpm', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('default_refunds_taxable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
