# Generated by Django 6.0 on 2025-12-30 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('companies', '0002_alter_company_options'),
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('mc_number', models.CharField(max_length=20, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Broker Company',
                'verbose_name_plural': 'Broker Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BrokerAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='operations.brokercompany')),
            ],
            options={
                'verbose_name': 'Broker Alias',
                'verbose_name_plural': 'Broker Aliases',
                'ordering': ['alias_name'],
                'unique_together': {('broker_company', 'alias_name')},
            },
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_number', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('settled', 'Settled')], default='dispatched', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_scheduled', models.DateTimeField(blank=True, null=True)),
                ('pickup_actual', models.DateTimeField(blank=True, null=True)),
                ('delivery_scheduled', models.DateTimeField(blank=True, null=True)),
                ('delivery_actual', models.DateTimeField(blank=True, null=True)),
                ('empty_location', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_location', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('base_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('miles', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('broker_alias', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loads', to='operations.brokeralias')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loads', to='companies.company')),
                ('dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loads', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loads', to='drivers.driver')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loads', to='assets.trailer')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loads', to='assets.truck')),
            ],
            options={
                'verbose_name': 'Load',
                'verbose_name_plural': 'Loads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoadCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('base', 'Base Rate'), ('lumper', 'Lumper'), ('detention', 'Detention'), ('layover', 'Layover'), ('tonu', 'TONU'), ('other', 'Other'), ('refund', 'Refund')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direction', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction'), ('refund', 'Refund')], max_length=10)),
                ('taxable', models.BooleanField(default=True, help_text='Refunds and Reimbursements are usually not taxable.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='operations.load')),
            ],
        ),
    ]
